[character]
symbol = "➜"
[directory]
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷‍"
stashed = "📦"
modified = "📝"
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
renamed = "👅"
deleted = "🗑"

[git_commit]
commit_hash_length = 4
